### ISSUE TITLE
get some errors: package does not exist . how do i fix those errors?

### ISSUE THREAD

**Issue by TreHack** [Whebcraft/Downloader#1]
/Users/tre_hack/Documents/downtest/myapp/platforms/android/src/com/org/apache/cordova/plugins/DownloadManager/DownloadManager/Downloader.java:43: 错误: 程序包org.apache.cordova.api不存在
import org.apache.cordova.api.CallbackContext;
                             ^
/Users/tre_hack/Documents/downtest/myapp/platforms/android/src/com/org/apache/cordova/plugins/DownloadManager/DownloadManager/Downloader.java:44: 错误: 程序包org.apache.cordova.api不存在
import org.apache.cordova.api.PluginResult;
                             ^
/Users/tre_hack/Documents/downtest/myapp/platforms/android/src/com/org/apache/cordova/plugins/DownloadManager/DownloadManager/Downloader.java:45: 错误: 程序包org.apache.cordova.api不存在
import org.apache.cordova.api.CordovaInterface

**Comment by Whebcraft** [comment]
@TreHack I just updated the code please try again
